### ISSUE TITLE
Multiple stations

### ISSUE THREAD

**Issue by SokolovskiR** [niklaskappler/MMM-vvsDeparture#10] opened 2020-01-04 13:39 UTC
Thanks for creating this nice module! I wanted to ask if there is a way to display departure information from several stations at a time.  When I add two modules on my smart mirror and configure them with different stations, they both display infromation for one single station only.

<img src="https://user-images.githubusercontent.com/59457122/71766351-67215f80-2eff-11ea-8bf1-f19465c97365.jpg" width="300">

My config.js

```
		{
			module: 'MMM-vvsDeparture',
            		position: "top_left",
            		config: {
                		station_id: 'de:08116:3459',
				//Esslingen, Lerchenaecker Endstation
				maximumEntries: "3"
				}
		},		
		{
			module: 'MMM-vvsDeparture',
            		position: "top_left",
            		config: {
                		station_id: 'de:08116:1802',
				//Esslingen, Oberesslingen
				maximumEntries: "3"
				}
		},

```

**Comment by chris-kwl** [comment] 2020-01-08 20:41
The problem is that the API requests are implemented in "node_helper.js", this applies to all module instances. In your case both stations are requested but the result is sent to all modules, so you can only see the first station for some ms/s. I have also noticed the problem and noted here #9 in my update.

I think to make it nice the module had to be changed completely, but I have created a workaround for myself. I just pushed it into my Fork: https://github.com/chris-kwl/MMM-vvsDeparture (Testspace for myself)
I simply added a ModuleID (mid) to differentiate the requests, the default mid is "1", so adding 'mid: 2' to your second module config would solve our problem for now.

**Comment by niklaskappler** [comment] 2020-01-09 22:11
Hi everyone,
showing multiple stations should be now possible with my lastest pushed fix. I choosed a different approach than @chris-kwl. Instead of adding a moduleID I use the unique module identifier as a message within the socket connection to be able to differentiate the request from `node_helper` within the modules. I tested the module the last days and it worked fine for me. Will close this issue for now, if you notice some bugs feel free to reopen this.

**Closed as completed by niklaskappler** 2020-01-09 22:11 UTC

**Comment by SokolovskiR** [comment] 2020-01-13 19:07
> Hi everyone,
> showing multiple stations should be now possible with my lastest pushed fix. I choosed a different approach than @chris-kwl. Instead of adding a moduleID I use the unique module identifier as a message within the socket connection to be able to differentiate the request from `node_helper` within the modules. I tested the module the last days and it worked fine for me. Will close this issue for now, if you notice some bugs feel free to reopen this.

@niklaskappler  Thanks, it works!
