### ISSUE TITLE
cancelled trains showing up delayed as "+NaN"

### ISSUE THREAD

**Issue by dnns92** [niklaskappler/MMM-vvsDeparture#6] opened 2019-08-29 18:06 UTC
Hey Niklas,

first of all, thank you for realizing this module. 
As there are major signal issues this week between Nordbahnhof and Zuffenhausen, the S6 is not leaving at all between Schwabstraße and Feuerbach. However though, the trains are showing up in the departing-timetable having a "+NaN"-Delay at each station. 
I suggest something similar to adding to line 123 of MMM-vvsDeparture.js
```
if (delay.getMinutes() == delay.getMinutes()) {
    delayWrapper.innerHTML = "+" + delay.getMinutes();
}
else {
    delayWrapper.innerHTML = "Canc";
}
```

**Comment by niklaskappler** [comment] 2019-08-30 10:09
Hey, 
thanks a lot for reporting. I'll take a look into this today evening and apply the fix. Let me check if there isn't a prettier solution to find out if that a connection is canceled via the API from VVS. Otherwise, I'll follow your suggestion.

**Comment by niklaskappler** [comment] 2019-08-31 15:27
Hi @dnns92,
had a look into it now and provided some fix, even though I can't reproduce your described behavior. I'll close this issue for now, if the fix won't work out feel free to reopen this.

**Closed as completed by niklaskappler** 2019-08-31 15:27 UTC
